#!/bin/bash

mac_address="$1"
file="$2"
handle="0x0021"

function error() {
  cat <<- EOH
    $1

    Usage: $0 <MAC address> <file>

    This tool will upload the file to the BlueBasic device that has that MAC address
    Need gatttool installed
	EOH
  exit 1
}


function upload_progress() {
  progress_character='='
  progress_length=20

  progress_step=$((100/progress_length))

  if (($1 >= progress_step)); then
    percent_bar="$(head -c "$(($1/progress_step))" < /dev/zero | tr '\0' $progress_character)"
    percent_bar="${percent_bar}$(printf "%$((progress_length-($1/progress_step)))s")"
  else
    percent_bar="$(printf "%${progress_length}s")"
  fi

  printf "\rUploading... [%s] (%s%%)" "$percent_bar" "$1"
}


function load() {
  hexdump=""
  chunks=()
  eol=13

  while read line; do
    line=$(printf '%s\r' "$line" | xxd -p | tr -d '\n')
    hexdump+="$line"
  done < $file

  length=(${#hexdump})
  for ((chunk=0; chunk<length; )); do
    byte=0
    buffer=""
    for ((count=0; ((chunk<length && byte != eol && count < 20)); count++, chunk+=2)); do
      byte=("0x${hexdump:chunk:2}")
      buffer+="${hexdump:chunk:2}"
    done
    chunks+=("$buffer")
  done

  upload_progress 0

  for chunk in ${!chunks[@]}; do
    result="$(gatttool -i hci0 \
                       -a "$handle" \
                       -b "$mac_address" \
                       -n "${chunks[chunk]}" \
                       --char-write-req 2>&1)"
    if [[ "$result" == "Characteristic value was written successfully" ]]; then
      percentage=$(bc <<< "scale=2; ($((chunk+1))/${#chunks[@]})*100")
      upload_progress "${percentage%.*}"
    else
      printf "\n%s\n" "$result"
      exit 1
    fi
  done
  printf "\n"
}


if ! [[ "$mac_address" =~ ^([a-fA-F0-9]{2}:){5}[a-zA-Z0-9]{2}$ ]]; then
  error "Wrong MAC address! Example: AA:BB:CC:DD:EE:FF"
elif ! [[ -r $file && -f $file ]]; then
  error "No such file!"
else
  printf "using handle %s\n" "$handle"
  load
fi
