#!/bin/bash

mac_address="$1"
file="$2"

if [[ "$mac_address" =~ ^([a-fA-F0-9]{2}:){5}[a-zA-Z0-9]{2}$ && -r $file && -f $file ]]; then
  while read line; do
    line=$(printf '%s\r' "$line" | xxd -p)
    echo gatttool -i hci0 -b "$mac_address" --char-write-req -a 0x0031 -n "$line"
  done < $file
  exit
fi

cat <<- EOH
  Usage: $0 <MAC address> <file>

  This tool will upload the file to the BlueBasic device that has that MAC address
  Fixme: I can't properly document a script, please fix it before commiting to Master branch.
EOH
