#!/bin/bash

mac_address="$1"
file="$2"

function load() {
  while read line; do
    line=$(printf '%s\r' "$line" | xxd -p | tr -d '\n')
    gatttool -i hci0 -b "$mac_address" --char-write-req -a 0x0031 -n $line
  done < $file
}

if [[ ! "$mac_address" =~ ^([a-fA-F0-9]{2}:){5}[a-zA-Z0-9]{2}$ ]]; then
  error="Wrong MAC address! Example: AA:BB:CC:DD:EE:FF"
elif [[ ! -r $file && -f $file ]]; then
  error="No such file!"
else
  load
  exit
fi

cat <<- EOH
  $error

  Usage: $0 <MAC address> <file>

  This tool will upload the file to the BlueBasic device that has that MAC address
  Need gatttool installed
EOH
